/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/breadcrumb/index.vue')['default']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    GlobalSetting: typeof import('./src/components/global-setting/index.vue')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    MonacoEditor: typeof import('./src/components/monaco-editor/monaco-editor.vue')['default']
    Navbar: typeof import('./src/components/navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Theme: typeof import('./src/components/theme/index.vue')['default']
    TinyActionMenu: typeof import('@opentiny/vue')['ActionMenu']
    TinyAlert: typeof import('@opentiny/vue')['Alert']
    TinyButton: typeof import('@opentiny/vue')['Button']
    TinyCol: typeof import('@opentiny/vue')['Col']
    TinyDrawer: typeof import('@opentiny/vue')['Drawer']
    TinyGrid: typeof import('@opentiny/vue')['Grid']
    TinyGridColumn: typeof import('@opentiny/vue')['GridColumn']
    TinyGridToolbar: typeof import('@opentiny/vue')['GridToolbar']
    TinyLayout: typeof import('@opentiny/vue')['Layout']
    TinyModal: typeof import('@opentiny/vue')['Modal']
    TinyOption: typeof import('@opentiny/vue')['Option']
    TinyRow: typeof import('@opentiny/vue')['Row']
    TinySearch: typeof import('@opentiny/vue')['Search']
    TinySelect: typeof import('@opentiny/vue')['Select']
    TinyTag: typeof import('@opentiny/vue')['Tag']
    TinyTooltip: typeof import('@opentiny/vue')['Tooltip']
  }
}
